from .consulta_1 import *
from .consulta_2 import *
from .consulta_3 import *
from .consulta_4 import *
from .consulta_5 import *
from .consulta_6 import *
from .consulta_7 import *
from .consulta_8 import *
from .consulta_9 import *
from .consulta_10 import *